### PR TITLE
Fix 0002-proton_LFH.mypatch not being applied

### PR DESCRIPTION
**Pull request by SegoGithub**
https://github.com/Frogging-Family/wine-tkg-git/issues/889

### CODE REVIEW

**Comment by SegoGithub** [comment]
I just realized this isn't the best way to do this, maybe instead of removing the 0002-proton_LFH.mypatch that prevents wine from compiling, maybe patch wine-tkg-git so it clones an older version of wine that works with 0002-proton_LFH.mypatch

**Comment by NyanCatTW1** [comment]
As LFH is essential in keeping the game running smooth for a longer period of time, I would rather wait for the issue to be fixed upstream than to outright remove the patch.

In case someone wants to build recent Wine with LFH support, you may do one of the following:
1. Set _plain_version to ef25dd2446e9c39b71a6199d8235a3734d1d20b4
2. Set _staging_version to 49ed7ae4a001a5d84141f65064081cce3c136137
Do 2. if you are building staging, or 1. if you are building mainline.

I'll keep this PR open until the patch gets rebased upstream

**Comment by Luciogi** [comment]
This should not need anymore, 0002-proton_LFH.mypatch is rebased on upstream

**Comment by NyanCatTW1** [comment]
Finally!

**Comment by SegoGithub** [comment]
finally
gonna update the aur package

**Pull request closed without merging**
